### ISSUE TITLE
windows下训练报错

### ISSUE THREAD

**Issue by ZJDATY** [Peterande/D-FINE#21]
请尽快推出windows下的训练教程。

```
(py310) D:\pyworkspaces\D-FINE>torchrun --master_port=7777 --nproc_per_node=4 train.py -c configs\dfine\dfine_hgnetv2_l_coco.yml --use-amp --seed=0 -t model.pth
W1101 18:25:56.674000 27360 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
W1101 18:25:56.746000 27360 torch\distributed\run.py:779]
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] *****************************************
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your systembeing overloaded, please further tune the variable for optimal performance in your application as needed.
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] *****************************************
Traceback (most recent call last):
  File "\\?\D:\ProgramData\anaconda3\envs\py310\Scripts\torchrun-script.py", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.1', 'console_scripts', 'torchrun')())
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\run.py", line 901, in main
    run(args)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\run.py", line 892, in run
    elastic_launch(
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\launcher\api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\launcher\api.py", line 255, in launch_agent
    result = agent.run()
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 680, in run
    result = self._invoke_run(role)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

```(py310) D:\pyworkspaces\D-FINE>torchrun --master_port=7777 --nproc_per_node=4 train.py -c configs\dfine\dfine_hgnetv2_l_coco.yml --use-amp --seed=0 -t model.pth
W1101 18:25:56.674000 27360 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
W1101 18:25:56.746000 27360 torch\distributed\run.py:779]
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] *****************************************
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your systembeing overloaded, please further tune the variable for optimal performance in your application as needed.
W1101 18:25:56.746000 27360 torch\distributed\run.py:779] *****************************************
Traceback (most recent call last):
  File "\\?\D:\ProgramData\anaconda3\envs\py310\Scripts\torchrun-script.py", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.1', 'console_scripts', 'torchrun')())
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\run.py", line 901, in main
    run(args)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\run.py", line 892, in run
    elastic_launch(
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\launcher\api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\launcher\api.py", line 255, in launch_agent
    result = agent.run()
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 680, in run
    result = self._invoke_run(role)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "D:\ProgramData\anaconda3\envs\py310\Lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

**Comment by HebeiFast** [comment]
看起来可能是安装的问题，可以参考该链接https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2227进行尝试解决。我们更加推荐你使用linux系统，方便之后的训练和部署。

**Comment by ZJDATY** [comment]
> 看起来是启动的问题，可以参考该链接[RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2227](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2227) 进行尝试解决。我们更加推荐你使用linux系统，方便之后的训练和部署。

![image](https://github.com/user-attachments/assets/4327479a-1ed6-4514-9b96-e2e9bbee42df)
它这里可以设置 set USE_LIBUV=0 但是我尝试了在torchrun之前运行 set USE_LIBUV=0 ，它还是会报相同的错误。你知道哪边用到了这个libuv，我可以手动禁用它吗？ 此外，我想多说一句， 如果本项目无法在windows下良好使用的话，我们会丢失很多应用场景。

**Comment by Peterande** [comment]
https://github.com/Peterande/D-FINE/blob/04c8844e012f9096c60a14082db59af3e2c9cc81/src/misc/dist_utils.py#L43

init_method="env://" -> init_method="env://?use_libuv=False"

**Comment by Peterande** [comment]
因为我们没有windows的多卡环境，暂时可能没法立即更新相关教程。关于应用场景的拓展，可能需要社区小伙伴的共同努力，我们也会做好配合，望理解~

**Comment by ZJDATY** [comment]
> https://github.com/Peterande/D-FINE/blob/04c8844e012f9096c60a14082db59af3e2c9cc81/src/misc/dist_utils.py#L43
> 
> `init_method="env://" `->  `init_method="env://?use_libuv=False"`

![image](https://github.com/user-attachments/assets/868019f8-6502-4a15-8b26-09f071d3503d)
![image](https://github.com/user-attachments/assets/73daa76c-7db1-4f05-8111-b47157d18169)
我修改 保存了 ，还是不行

**Comment by ZJDATY** [comment]
> 因为我们没有windows的多卡环境，暂时可能没法立即更新相关教程。关于应用场景的拓展，可能需要社区小伙伴的共同努力，我们也会做好配合，望理解~

能否先出一个windows下单卡训练的教程， 大部分windows下都是单卡进行训练的，我也是只有单卡

**Comment by Peterande** [comment]
我查阅了一下相关的报错解决办法。这本质上可能是torch某版本自身的问题，很多人通过更换版本解决了，与D-FINE的代码可能无关。

**Comment by Peterande** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/1357

**Comment by Peterande** [comment]
Glad to hear that~

**Comment by Kaze816** [comment]
> > 因为我们没有windows的多卡环境，暂时可能没法立即更新相关教程。关于应用场景的拓展，可能需要社区小伙伴的共同努力，我们也会做好配合，望理解~
> 
> 能否先出一个windows下单卡训练的教程， 大部分windows下都是单卡进行训练的，我也是只有单卡

把train.py 里面以下位置修改成这样就好了

`def main(args, ) -> None:
    """main
    """
    # dist_utils.setup_distributed(args.print_rank, args.print_method, seed=args.seed)
    # os.environ['MASTER_ADDR'] = 'localhost'
    # os.environ['MASTER_PORT'] = '12345'
    # torch.distributed.init_process_group(backend='nccl',rank=0, world_size = 1)
    torch.cuda.set_device("cuda:0")
...
`
