### ISSUE TITLE
增大D-FINE模型推理的尺寸

### ISSUE THREAD

**Issue by a773783082** [Peterande/D-FINE#71]
我用预训练的权重，直接修改torch_inf.py中Resize的尺寸为`800x800`，推理会报错，想问下是不是只能固定推理尺寸和训练时的输入尺寸一样？

**Comment by a773783082** [comment]
推理成功了，还得改2个地方，按照之前跑DETR的经验，修改了模型eval_spatial_size里面的尺寸，此外还得把权重pth里面的`decoder.anchors`和`decoder.valid_mask`权重删掉，之前是因为这两个权重的shape不匹配报的错
```
## 1. dfine_hgnetv2.yaml
eval_spatial_size: [800, 800] # h w 改成目标尺寸

## 2. 修改预处理尺寸，同时删除2个权重 torch_inf.py
def process_image(model, device, file_path):
    ...
    transforms = T.Compose([
        T.Resize((800, 800)),
        T.ToTensor(),
    ])

def main(args):
    ...
    # Load train mode state and convert to deploy mode
    del state["decoder.anchors"]
    del state["decoder.valid_mask"]
    cfg.model.load_state_dict(state, strict=False)
```

**Comment by JunerLee** [comment]
> 推理成功了，还得改2个地方，按照之前跑DETR的经验，修改了模型eval_spatial_size里面的尺寸，此外还得把权重pth里面的`decoder.anchors`和`decoder.valid_mask`权重删掉，之前是因为这两个权重的shape不匹配报的错
> 
> ```
> ## 1. dfine_hgnetv2.yaml
> eval_spatial_size: [800, 800] # h w 改成目标尺寸
> 
> ## 2. 修改预处理尺寸，同时删除2个权重 torch_inf.py
> def process_image(model, device, file_path):
>     ...
>     transforms = T.Compose([
>         T.Resize((800, 800)),
>         T.ToTensor(),
>     ])
> 
> def main(args):
>     ...
>     # Load train mode state and convert to deploy mode
>     del state["decoder.anchors"]
>     del state["decoder.valid_mask"]
>     cfg.model.load_state_dict(state, strict=False)
> ```

楼主你好，请问下trt_inf.py用tensorrt加速推理的这个你跑成功了吗，我1280训练的，torch版本能推理成功，trt这个就会报错:
Traceback (most recent call last):
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 226, in <module>
    process_image(m, file_path, args.device)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 151, in process_image
    output = m(blob)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 109, in __call__
    return self.run_torch(blob)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 99, in run_torch
    assert self.bindings[n].data.dtype == blob[n].dtype, '{} dtype mismatch'.format(n)
AssertionError: orig_target_sizes dtype mismatch
