### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by HandsLing** [Peterande/D-FINE#74]
stop_epoch设置为1 训练1个epoch之后报错，错误信息如下：
Traceback (most recent call last):
  File "/data_out_g/lingck/D-FINE/train.py", line 84, in <module>
    main(args)
  File "/data_out_g/lingck/D-FINE/train.py", line 54, in main
    solver.fit()
  File "/data_out_g/lingck/D-FINE/src/solver/det_solver.py", line 60, in fit
Traceback (most recent call last):
  File "/data_out_g/lingck/D-FINE/train.py", line 84, in <module>
    main(args)
  File "/data_out_g/lingck/D-FINE/train.py", line 54, in main
    solver.fit()
  File "/data_out_g/lingck/D-FINE/src/solver/det_solver.py", line 60, in fit
    self.load_resume_state(path)
  File "/data_out_g/lingck/D-FINE/src/solver/_solver.py", line 160, in load_resume_state
    self.load_resume_state(path)
  File "/data_out_g/lingck/D-FINE/src/solver/_solver.py", line 160, in load_resume_state
    state = torch.load(path)
            ^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/25inone_20421122/best_stg1.pth'
    state = torch.load(path)
            ^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/25inone_20421122/best_stg1.pth'
Traceback (most recent call last):
  File "/data_out_g/lingck/D-FINE/train.py", line 84, in <module>
    main(args)
  File "/data_out_g/lingck/D-FINE/train.py", line 54, in main
    solver.fit()
  File "/data_out_g/lingck/D-FINE/src/solver/det_solver.py", line 60, in fit
    self.load_resume_state(path)
  File "/data_out_g/lingck/D-FINE/src/solver/_solver.py", line 160, in load_resume_state
    state = torch.load(path)
            ^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingchengkun/anaconda3/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/25inone_20421122/best_stg1.pth'

但是我看  output/25inone_20421122/best_stg1.pth 这个文件是在的，而且单独用torch.load加载进来是可以的，单卡训练也不会报这样的错

**Comment by Peterande** [comment]
我这边多卡没遇到过这个问题，所以没法复现(இωஇ )

**Comment by zhangyupeng123** [comment]
@HandsLing 我也出现了这个问题，请问你的解决了吗~
