### ISSUE TITLE
Encounter an error at the beginning of epoch 72

### ISSUE THREAD

**Issue by wusheng816** [Peterande/D-FINE#75]
**When I am trainning on the custom datasets,  encounters an error at the beginning of epoch 72.**

Epoch: [71] Total time: 0:26:06 (0.5305 s / it)
Averaged stats: lr: 0.000013  loss: 24.2908 (24.7197)  loss_bbox: 0.0855 (0.0863)  loss_bbox_aux_0: 0.0913 (0.0907)  loss_bbox_aux_1: 0.0873 (0.0875)  loss_bbox_aux_2: 0.0851 (0.0864)  loss_bbox_aux_3: 0.0856 (0.0861)  loss_bbox_aux_4: 0.0855 (0.0863)  loss_bbox_dn_0: 0.0837 (0.0890)  loss_bbox_dn_1: 0.0643 (0.0653)  loss_bbox_dn_2: 0.0649 (0.0623)  loss_bbox_dn_3: 0.0643 (0.0614)  loss_bbox_dn_4: 0.0643 (0.0614)  loss_bbox_dn_5: 0.0643 (0.0614)  loss_bbox_dn_pre: 0.0852 (0.0890)  loss_bbox_enc_0: 0.1101 (0.1039)  loss_bbox_pre: 0.0915 (0.0905)  loss_ddf_aux_0: 0.3251 (0.2060)  loss_ddf_aux_1: 0.0445 (0.0637)  loss_ddf_aux_2: 0.0305 (0.0412)  loss_ddf_aux_3: 0.0283 (0.0389)  loss_ddf_aux_4: 0.0000 (0.0000)  loss_ddf_dn_0: 0.5076 (0.4588)  loss_ddf_dn_1: 0.2620 (0.0899)  loss_ddf_dn_2: 0.0616 (0.0437)  loss_ddf_dn_3: 0.0007 (0.0012)  loss_ddf_dn_4: 0.0000 (0.0000)  loss_fgl: 0.9900 (1.0168)  loss_fgl_aux_0: 1.0112 (1.0394)  loss_fgl_aux_1: 0.9865 (1.0176)  loss_fgl_aux_2: 0.9807 (1.0148)  loss_fgl_aux_3: 0.9807 (1.0144)  loss_fgl_aux_4: 0.9900 (1.0167)  loss_fgl_dn_0: 1.1006 (1.1056)  loss_fgl_dn_1: 0.9726 (0.9904)  loss_fgl_dn_2: 0.9660 (0.9797)  loss_fgl_dn_3: 0.9645 (0.9782)  loss_fgl_dn_4: 0.9647 (0.9780)  loss_fgl_dn_5: 0.9648 (0.9780)  loss_giou: 0.2938 (0.3455)  loss_giou_aux_0: 0.3105 (0.3636)  loss_giou_aux_1: 0.2966 (0.3505)  loss_giou_aux_2: 0.2932 (0.3460)  loss_giou_aux_3: 0.2929 (0.3451)  loss_giou_aux_4: 0.2937 (0.3455)  loss_giou_dn_0: 0.3071 (0.3405)  loss_giou_dn_1: 0.2330 (0.2588)  loss_giou_dn_2: 0.2267 (0.2493)  loss_giou_dn_3: 0.2262 (0.2468)  loss_giou_dn_4: 0.2260 (0.2467)  loss_giou_dn_5: 0.2260 (0.2467)  loss_giou_dn_pre: 0.3043 (0.3393)  loss_giou_enc_0: 0.3657 (0.4107)  loss_giou_pre: 0.3078 (0.3621)  loss_vfl: 0.3724 (0.3974)  loss_vfl_aux_0: 0.3977 (0.4203)  loss_vfl_aux_1: 0.3737 (0.4098)  loss_vfl_aux_2: 0.3702 (0.4037)  loss_vfl_aux_3: 0.3715 (0.3970)  loss_vfl_aux_4: 0.3682 (0.3973)  loss_vfl_dn_0: 0.4001 (0.3985)  loss_vfl_dn_1: 0.3125 (0.3189)  loss_vfl_dn_2: 0.3007 (0.3095)  loss_vfl_dn_3: 0.2987 (0.3069)  loss_vfl_dn_4: 0.3006 (0.3069)  loss_vfl_dn_5: 0.2996 (0.3068)  loss_vfl_dn_pre: 0.3999 (0.3991)  loss_vfl_enc_0: 0.4292 (0.4503)  loss_vfl_pre: 0.3876 (0.4201)
Test:  [  0/164]  eta: 0:05:13    time: 1.9095  data: 1.6223  max mem: 22481
Test:  [ 10/164]  eta: 0:01:12    time: 0.4694  data: 0.1921  max mem: 22481
Test:  [ 20/164]  eta: 0:01:01    time: 0.3542  data: 0.0504  max mem: 22481
Test:  [ 30/164]  eta: 0:00:54    time: 0.3724  data: 0.0519  max mem: 22481
Test:  [ 40/164]  eta: 0:00:48    time: 0.3439  data: 0.0488  max mem: 22481
Test:  [ 50/164]  eta: 0:00:43    time: 0.3379  data: 0.0464  max mem: 22481
Test:  [ 60/164]  eta: 0:00:39    time: 0.3502  data: 0.0476  max mem: 22481
Test:  [ 70/164]  eta: 0:00:34    time: 0.3354  data: 0.0480  max mem: 22481
Test:  [ 80/164]  eta: 0:00:30    time: 0.3287  data: 0.0472  max mem: 22481
Test:  [ 90/164]  eta: 0:00:26    time: 0.3379  data: 0.0472  max mem: 22481
Test:  [100/164]  eta: 0:00:22    time: 0.3268  data: 0.0478  max mem: 22481
Test:  [110/164]  eta: 0:00:19    time: 0.3252  data: 0.0470  max mem: 22481
Test:  [120/164]  eta: 0:00:15    time: 0.3206  data: 0.0465  max mem: 22481
Test:  [130/164]  eta: 0:00:11    time: 0.3211  data: 0.0472  max mem: 22481
Test:  [140/164]  eta: 0:00:08    time: 0.3413  data: 0.0473  max mem: 22481
Test:  [150/164]  eta: 0:00:04    time: 0.3425  data: 0.0479  max mem: 22481
Test:  [160/164]  eta: 0:00:01    time: 0.3401  data: 0.0463  max mem: 22481
Test:  [163/164]  eta: 0:00:00    time: 0.3452  data: 0.0457  max mem: 22481
Test: Total time: 0:00:57 (0.3486 s / it)
Averaged stats: 
Accumulating evaluation results...
DONE (t=8.58s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.651
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.923
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.707
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.597
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.764
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.700
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.254
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.611
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.745
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.692
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.844
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.838
/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py:159: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location='cpu')
/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py:159: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location='cpu')
/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py:159: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location='cpu')
[rank3]: Traceback (most recent call last):
[rank3]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 84, in <module>
[rank3]:     main(args)
[rank3]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 54, in main
[rank3]:     solver.fit()
[rank3]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/det_solver.py", line 42, in fit
[rank3]:     self.load_resume_state(str(self.output_dir / 'best.pth'))
[rank3]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py", line 159, in load_resume_state
[rank3]:     state = torch.load(path, map_location='cpu')
[rank3]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1384, in load
[rank3]:     return _legacy_load(
[rank3]:            ^^^^^^^^^^^^^
[rank3]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1628, in _legacy_load
[rank3]:     magic_number = pickle_module.load(f, **pickle_load_args)
[rank3]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: EOFError: Ran out of input
[rank1]: Traceback (most recent call last):
[rank1]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 84, in <module>
[rank1]:     main(args)
[rank1]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 54, in main
[rank1]:     solver.fit()
[rank1]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/det_solver.py", line 42, in fit
[rank1]:     self.load_resume_state(str(self.output_dir / 'best.pth'))
[rank1]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py", line 159, in load_resume_state
[rank1]:     state = torch.load(path, map_location='cpu')
[rank1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1384, in load
[rank1]:     return _legacy_load(
[rank1]:            ^^^^^^^^^^^^^
[rank1]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1628, in _legacy_load
[rank1]:     magic_number = pickle_module.load(f, **pickle_load_args)
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: EOFError: Ran out of input
[rank2]: Traceback (most recent call last):
[rank2]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 84, in <module>
[rank2]:     main(args)
[rank2]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/train.py", line 54, in main
[rank2]:     solver.fit()
[rank2]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/det_solver.py", line 42, in fit
[rank2]:     self.load_resume_state(str(self.output_dir / 'best.pth'))
[rank2]:   File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py", line 159, in load_resume_state
[rank2]:     state = torch.load(path, map_location='cpu')
[rank2]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1384, in load
[rank2]:     return _legacy_load(
[rank2]:            ^^^^^^^^^^^^^
[rank2]:   File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/serialization.py", line 1628, in _legacy_load
[rank2]:     magic_number = pickle_module.load(f, **pickle_load_args)
[rank2]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: EOFError: Ran out of input
best_stat: {'epoch': 71, 'coco_eval_bbox': 0.6506782846578031}
/share/home/defaultTenant/wsh/code/D-FINE-master/src/solver/_solver.py:159: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location='cpu')
Load last_epoch
Load model.state_dict
Load criterion.state_dict
Load postprocessor.state_dict
Load ema.state_dict
Load scaler.state_dict
Load optimizer.state_dict
Load lr_scheduler.state_dict
Load lr_warmup_scheduler.state_dict
Refresh EMA at epoch 72 with decay 0.9999
Exception ignored in atexit callbackException ignored in atexit callback: : Exception ignored in atexit callback: <function cleanup at 0x14c47d42ae80><function cleanup at 0x151fc238ae80>
<function cleanup at 0x152df7aaae80>
Traceback (most recent call last):
Traceback (most recent call last):

  File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/misc/dist_utils.py", line 100, in cleanup
Traceback (most recent call last):
  File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/misc/dist_utils.py", line 100, in cleanup
  File "/share/home/defaultTenant/wsh/code/D-FINE-master/src/misc/dist_utils.py", line 100, in cleanup
    torch.distributed.barrier()
    torch.distributed.barrier()
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    torch.distributed.barrier()
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)    
return func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 4164, in barrier
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 4164, in barrier
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 4164, in barrier
        work.wait()work.wait()

RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 1800000ms for send operation to completeRuntimeError
: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
[rank0]:[E1112 23:34:28.613510957 ProcessGroupNCCL.cpp:616] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=40402014, OpType=_ALLGATHER_BASE, NumelIn=513, NumelOut=2052, Timeout(ms)=1800000) ran for 1800046 milliseconds before timing out.
[rank0]:[E1112 23:34:28.617797496 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 40402014, last enqueued NCCL work: 40402014, last completed NCCL work: 40402013.
W1112 23:34:29.122000 2366719 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2366797 closing signal SIGTERM
W1112 23:34:29.125000 2366719 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2366798 closing signal SIGTERM
W1112 23:34:29.126000 2366719 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2366800 closing signal SIGTERM
E1112 23:34:29.740000 2366719 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 2366799) of binary: /share/home/defaultTenant/wsh/.conda/envs/dfine/bin/python
Traceback (most recent call last):
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/defaultTenant/wsh/.conda/envs/dfine/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-12_23:34:29
  host      : compute-03.hpc.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2366799)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by TychoBomer** [comment]
Hi, are you using distribute training?

It looks like the problem occurs when you use multiplexing, whhich can cause problems in distributed training with multiple GPUS.

How are you launching your code? You should try to launch it from a single entrypoint such as a terminal instead of using nohup or debuggers to launch it. Your error indicates launching with nohup might influence the distributed training.

**Comment by 1898ha** [comment]
Perhaps you can try using single GPU training; I also encountered the same issue, but it has been resolved.
