### ISSUE TITLE
trt_inf.py tensorrt推理加速出现orig_target_sizes不匹配的错误无法成功推理

### ISSUE THREAD

**Issue by JunerLee** [Peterande/D-FINE#76]
1. 我在训练的时候，将图像大小由640改为了1280，修改了图像大小相关的适配为1280,其他的没改,成功训练完毕
2. 训练好之后保存为best_stg2.pth，然后用官方的代码和命令转成best_stg2.onnx
3. 再将onnx用官方的命令转成engine文件，trtexec --onnx="best_stg2.onnx" --saveEngine="best_stg2.engine" --fp16
4. 最后运行官方的trt推理文件python tools/inference/trt_inf.py --trt best_stg2.engine --input image.jpg 
5. 结果就报错了，如下错误，Traceback (most recent call last):
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 226, in <module>
    process_image(m, file_path, args.device)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 151, in process_image
    output = m(blob)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 109, in __call__
    return self.run_torch(blob)
  File "/localdata/lj/code/D-FINE/tools/inference/trt_inf.py", line 99, in run_torch
    assert self.bindings[n].data.dtype == blob[n].dtype, '{} dtype mismatch'.format(n)
AssertionError: orig_target_sizes dtype mismatch
6. 我用tools/inference/torch_inf.py推理是成功的，而且效果相当不错（感谢作者们的工作）

**Comment by JunerLee** [comment]
> torch_inf.py 140-143 resize the input image to 640*640.

thanks, but I run with trt_inf.py not torch_inf.py,torch_inf.py is good for me.

**Comment by GiovanniFyc** [comment]
trt_inf.py 140-143 resize the input image to 640*640.if you want infer 1280*1280,please check it.

**Comment by JunerLee** [comment]
> trt_inf.py 140-143 resize the input image to 640_640.if you want infer 1280_1280,please check it.


yes, I changed the input to 1280, but whether I set it to 1280 or 640, I still get the same error. I suspect the issue might be related to a mismatch in data types, such as int32 or float32, during the model conversion process. All the conversion steps were followed strictly according to the README, but I am not very familiar with this project and am unsure how to troubleshoot.

**Comment by GiovanniFyc** [comment]
you can change trt_inf.py 138 to  orig_size = torch.tensor([w, h], dtype=torch.int32)[None].to(device)

**Comment by JunerLee** [comment]
> https://github.com/Peterande/D-FINE/pull/78/files

Thanks for thie PR, it works!
